### ISSUE TITLE
Get all underlying RICs within a chain RIC

### ISSUE THREAD

**Issue by kiranshm973** [devcartel/api#58]
Hi,

Is there a way to get all underlying RICs within a chain RIC? I am able to get a snapshot using marketPriceRequest for chain RIC 0#MIFID.xbp but not sure how to get all underlying RICs. 

Thanks,
Kiran

**Comment by wiwat-tharateeraparb** [comment]
Possible. Check out examples/chain.py

**Comment by kiranshm973** [comment]
thanks

**Comment by zwedwin** [comment]
hi @wiwat-tharateeraparb I have tried to implement this recursively but am running into issues 

here is my implementation

```
`def get_all_children(chain_ric, visited, rics):
    children, _ = expand_chain_ric(chain_ric)
    if chain_ric.endswith('.xbo') and not chain_ric.startswith('0#'):
        rics.add(chain_ric)
    children = [child for child in children if child not in visited]
    print('CHAIN RIC:   ' + chain_ric)
    if children:
        for child in children:
            if child in visited:
                pass
            visited.append(child)
            get_all_children(child, visited, rics)
    return None`
```

I appear to be missing some RICs however. I am expecting ~3500 constituent rics but I am only getting ~2000. From what I understand pyfra is no longer officially supported by refinitiv could this be causing the issue here? Are there RICS that "live on an island" so to speak and can only be accessed if you have the address? Thanks for your help.
